### ISSUE TITLE
Nyelvváltó rossz helyen van lezárva a <div>

### ISSUE THREAD

**Issue by swiss1111** [Locutus18/LAN#9]
<div id="international" style=": block; ">
		<div class="column">
			<ul>
				<li>
					<a href="?Local=en" tabindex="100" onclick="Locale.trackEvent('Change Language', 'en to en'); return true;">
						   English					</a>
				</li>
		</div>
		<div class="column">
			<ul>
				<li>
					<a href="?Local=hu" tabindex="100" onclick="Locale.trackEvent('Change Language', 'en to hu'); return true;">
						   Magyar					</a>
				</li>
			</ul>
		</div>
</div>

**Comment by Locutus18** [comment]
Javítva :) Kövileg assignee-old rám :) Plusz javítottam a menüpontok szövegét. Lerövidítettem.
